globalThis.window = globalThis;
const ctxStub = new Proxy({}, { get: (t, k) => (k === 'canvas' ? { width: 1, height: 1 } : k === 'measureText' ? () => ({ width: 10 }) : () => ctxStub), set: () => true });
globalThis.document = { createElement: () => ({ width: 1, height: 1, getContext: () => ctxStub, style: {} }) };
globalThis.localStorage = { getItem: () => null, setItem() {} };
const THREE = await import('three');
const warn = console.log; console.error = (...a) => { warn(String(a[0]).slice(0, 80), new Error().stack.split('\n').slice(2, 6).join(' | ')); };
const { TRACKS } = await import('../src/tracks/index.js');
const { buildTrack } = await import('../src/tracks/build.js');
const { COTA } = await import('../src/render3d/worlds/cota.js');
const K = await import('../src/render3d/worlds/cota-kit.js'); const ot = K.Mesher.prototype.tri; K.Mesher.prototype.tri = function(a,b,c,C){ for(const p of [a,b,c]) if(p.some(v=>!isFinite(v))||!C||!isFinite(C.r)){ console.log('NaN tri', JSON.stringify([a,b,c]), new Error().stack.split('\n').slice(2,5).join(' | ')); process.exit(); } return ot.call(this,a,b,c,C); };
const T = buildTrack(TRACKS.find(t => t.id === 'cota'));
const scene = new THREE.Scene(), world = new THREE.Group(); scene.add(world);
COTA.build({ sun: { color: new THREE.Color() }, scene }, world, T, { clock: 0, cars: [] });
